version: "3.7"

services:
  Aria2:
    container_name: Aria2
    image: p3terx/aria2-pro:latest
    network_mode: host
    log-opt: max-size=1m
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=<>
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=<256M>
    volumes:
      - /aria2/config:/config
      - /aria2/downloads:/downloads
    restart: unless-stopped
