version: "3.7"

services:
  Aria2:
    container_name: Aria2
    image: p3terx/aria2-pro:latest
    network_mode: "host"
    volumes:
      - /aria2/config:/config
      - /aria2/downloads:/downloads
    env_file:
      - config.env
    expose:
      - 6800
      - 6888
    restart: unless-stopped
